spring:
  application:
    name: green-mile
green-mile:
  config:
    application-id: green-mile
    bootstrap-servers: broker:9092
    state-dir: ./target
    properties:
      default:
        key:
          serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        value:
          serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      commit:
        interval:
          ms: 1000
